APIURL = "https://open-api.bingx.com"

keys = [
    
]

POPULAR_SYMBOLS = ["BTC-USDT", "ETH-USDT", "XRP-USDT", "BNB-USDT", "ALCH-USDT", "SOL-USDT", "DOGE-USDT", "TIA-USDT", "ADA-USDT", "LTC-USDT", "LINK-USDT", "DOT-USDT", "HOT-USDT", "SHIB-USDT", "AVAX-USDT", "BCH-USDT", "MKR-USDT", "UNI-USDT", "AAVE-USDT", "SUSHI-USDT"]
PRICE_HISTORY_SIZE = 20